const defaultCategoriesMap = {
  'tantuni': { name: 'Tantuni Ürünleri', icon: '<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M16.5 5.5l-9 9c-.8.8-.8 2 0 2.8l2.2 2.2c.8.8 2 .8 2.8 0l9-9c.8-.8.8-2 0-2.8l-2.2-2.2c-.8-.8-2-.8-2.8 0z" /><path d="M14 6.5l3.5 3.5" fill="none" stroke="currentColor" stroke-width="1.5" /><path d="M17.5 16.5c-1-1-2.5-.5-3 1-.3.8-.2 1.8.3 2.5.5.7 1.5 1.2 2.2.8.8-.4.8-1.5.5-2.3-.3-.8 0-1.5 0-2z" /><path d="M6.5 18.5c-3-2.5-4-6.5-2.5-10.5C5.5 4 9.5 1.5 13.5 2" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>' },
  'tavuk': { name: 'Tavuk Ürünleri', icon: '<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M10 3h2v18h-2z"/><path d="M6 6c0-.5.5-1 1-1h6c.5 0 1 .5 1 1v1c0 .5-.5 1-1 1H7c-.5 0-1-.5-1-1V6zM6.5 8c0-.5.5-1 1-1h5c.5 0 1 .5 1 1v1.5c0 .5-.5 1-1 1h-5c-.5 0-1-.5-1-1V8zM7 11.5c0-.5.5-1 1-1h4c.5 0 1 .5 1 1V13c0 .5-.5 1-1 1H8c-.5 0-1-.5-1-1v-1.5zM7.5 14.5c0-.5.5-1 1-1h3c.5 0 1 .5 1 1v1.5c0 .5-.5 1-1 1h-3c-.5 0-1-.5-1-1v-1.5zM8 17.5c0-.5.5-1 1-1h2c.5 0 1 .5 1 1v1c0 .5-.5 1-1 1H9c-.5 0-1-.5-1-1v-1z"/><path d="M15.5 13.5c0 0 .5-1.5 1.5-2 .5-.2.5-.5.5-.8 0-.5-.3-.7-.7-.7-.3 0-.6.1-.9.3-.3-1 .2-2.3.8-2.8.3-.3.8-.5 1.2-.4s.7.4.8.8c.2.8.2 1.6-.2 2.3.3.5.7.8 1 .8.5 0 1.2-.5 1.5-.8.2.5.3 1.1.2 1.7-.2.8-.7 1.3-1.3 1.5-.6.2-1.3.1-1.8-.2-.3.3-.6.7-1 .9-.3.2-.6.3-.9.3-.7 0-1.2-.6-1.2-1.4z"/><path d="M5.5 19.5c-3-2.5-4-6.5-2.5-10.5C4.5 5 8.5 2.5 12.5 3" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>' },
  'et': { name: 'Et Ürünleri', icon: '<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M10 3h2v18h-2z"/><path d="M6 6c0-.5.5-1 1-1h6c.5 0 1 .5 1 1v1c0 .5-.5 1-1 1H7c-.5 0-1-.5-1-1V6zM6.5 8c0-.5.5-1 1-1h5c.5 0 1 .5 1 1v1.5c0 .5-.5 1-1 1h-5c-.5 0-1-.5-1-1V8zM7 11.5c0-.5.5-1 1-1h4c.5 0 1 .5 1 1V13c0 .5-.5 1-1 1H8c-.5 0-1-.5-1-1v-1.5zM7.5 14.5c0-.5.5-1 1-1h3c.5 0 1 .5 1 1v1.5c0 .5-.5 1-1 1h-3c-.5 0-1-.5-1-1v-1.5zM8 17.5c0-.5.5-1 1-1h2c.5 0 1 .5 1 1v1c0 .5-.5 1-1 1H9c-.5 0-1-.5-1-1v-1z"/><path d="M15.5 10c0 0 .5-1.5 1-2.5.2-.4.6-.7 1-.7.5 0 .8.3.9.7.1.5-.1 1-.4 1.5h1c.6 0 1 .4 1 1v2c0 1.1-.9 2-2 2h-1c-.5.8-1.3 1.3-2.3 1.3-1.5 0-2.2-.8-2.2-1.8 0-.5.2-1 .5-1.3l-1.5-1.2v-1z"/><path d="M5.5 19.5c-3-2.5-4-6.5-2.5-10.5C4.5 5 8.5 2.5 12.5 3" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>' },
  'diger': { name: 'İçecekler ve Yan Ürünler', icon: '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 8h1a4 4 0 1 1 0 8h-1"/><path d="M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V8z"/><line x1="6" y1="2" x2="6" y2="4"/><line x1="10" y1="2" x2="10" y2="4"/><line x1="14" y1="2" x2="14" y2="4"/></svg>' }
};

const defaultItemTranslations = {
  'katik-tavuk-menu-1': {
    name: 'Katik Chicken Doner Wrap Menu 1',
    description: 'Katik chicken doner wrap, served with french fries and ayran (300 ml).',
    ingredients: 'Chicken doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices. Menu includes french fries and drink (or ayran).'
  },
  'katik-tavuk-menu-2': {
    name: 'Katik Chicken Doner Wrap Menu 2',
    description: 'Katik chicken doner wrap, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Chicken doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices. Menu includes french fries and drink (or ayran).'
  },
  'zurna-tavuk-menu-1': {
    name: 'Zurna Chicken Menu 1',
    description: 'Satisfying zurna chicken doner wrap, served with french fries and ayran (300 ml).',
    ingredients: 'Chicken doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices. Menu includes french fries and drink (or ayran).'
  },
  'zurna-tavuk-menu-2': {
    name: 'Zurna Chicken Menu 2',
    description: 'Satisfying zurna chicken doner wrap, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Chicken doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices. Menu includes french fries and drink (or ayran).'
  },
  'katik-et-menu-1': {
    name: 'Katik Beef Menu 1',
    description: 'Katik beef doner wrap, served with french fries and ayran (300 ml).',
    ingredients: 'Beef doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices. Menu includes french fries and drink (or ayran).'
  },
  'katik-et-menu-2': {
    name: 'Katik Beef Menu 2',
    description: 'Katik beef doner wrap, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Beef doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices. Menu includes french fries and drink (or ayran).'
  },
  'combo-tavuk-menu-1': {
    name: 'Combo Chicken Menu 1',
    description: '1 Katik Chicken Wrap + 1 Chicken Tantuni Wrap, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Chicken doner, chicken tantuni, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices.'
  },
  'combo-tavuk-menu-2': {
    name: 'Combo Chicken Menu 2',
    description: '2 Katik Chicken Wraps, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Chicken doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices.'
  },
  'combo-et-menu-1': {
    name: 'Combo Beef Menu 1',
    description: '1 Katik Beef Wrap + 1 Beef Tantuni Wrap, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Beef doner, beef tantuni, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices.'
  },
  'combo-et-menu-2': {
    name: 'Combo Beef Menu 2',
    description: '2 Katik Beef Wraps, served with french fries and canned soft drink (330 ml).',
    ingredients: 'Beef doner, french fries, special Katik sauce, wheat flour lavash (contains gluten) or bread, vegetable oil, salt, spices.'
  },
  'et-tantuni-durum': {
    name: 'Beef Tantuni Wrap',
    description: 'Traditional beef tantuni wrap with tomatoes, parsley, onions, and spices.',
    ingredients: 'Beef meat, tomatoes, parsley, onion, special spices, wheat flour lavash (contains gluten).'
  },
  'et-tantuni-ekmek-arasi': {
    name: 'Beef Tantuni Sandwich',
    description: 'Tasty beef tantuni in a bread roll with tomatoes, parsley, onions, and spices.',
    ingredients: 'Beef meat, tomatoes, parsley, onion, special spices, sandwich bread (contains gluten).'
  },
  'yogurtlu-et-tantuni': {
    name: 'Beef Tantuni with Yogurt',
    description: 'Beef tantuni served over sliced bread with yogurt, hot butter, and tomato sauce.',
    ingredients: 'Beef meat, yogurt, special tomato sauce, melted butter, sliced bread (contains gluten), parsley.'
  },
  'tavuk-tantuni-durum': {
    name: 'Chicken Tantuni Wrap',
    description: 'Chicken tantuni wrap with tomatoes, parsley, onions, and spices.',
    ingredients: 'Chicken meat, tomatoes, parsley, onion, special spices, wheat flour lavash (contains gluten).'
  },
  'tavuk-tantuni-ekmek-arasi': {
    name: 'Chicken Tantuni Sandwich',
    description: 'Chicken tantuni in a bread roll with tomatoes, parsley, onions, and spices.',
    ingredients: 'Chicken meat, tomatoes, parsley, onion, special spices, sandwich bread (contains gluten).'
  },
  'tavuk-tantuni-yogurtlu': {
    name: 'Chicken Tantuni with Yogurt',
    description: 'Chicken tantuni served over sliced bread with yogurt, hot butter, and tomato sauce.',
    ingredients: 'Chicken meat, yogurt, special tomato sauce, melted butter, sliced bread (contains gluten), parsley.'
  },
  'zurna-mantarli-durum': {
    name: 'Zurna Chicken Wrap with Mushrooms',
    description: 'Zurna chicken doner wrap with special mushroom sauce and greens.',
    ingredients: 'Chicken doner, special mushroom sauce, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'zurna-cheddarli-tavuk-durum': {
    name: 'Zurna Chicken Wrap with Cheddar',
    description: 'Zurna chicken doner wrap with melted cheddar cheese and greens.',
    ingredients: 'Chicken doner, melted cheddar cheese, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'zurna-kasarli-tavuk-durum': {
    name: 'Zurna Chicken Wrap with Kashar',
    description: 'Zurna chicken doner wrap with melted kashar cheese and greens.',
    ingredients: 'Chicken doner, melted kashar cheese, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'katik-barbeku-soslu-zurna-tavuk': {
    name: 'Katik BBQ Zurna Chicken Wrap',
    description: 'Zurna chicken doner wrap with special BBQ sauce and greens.',
    ingredients: 'Chicken doner, special BBQ sauce, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'katik-barbeku-soslu-tavuk-durum': {
    name: 'Katik BBQ Chicken Wrap',
    description: 'Standard chicken doner wrap with BBQ sauce and greens.',
    ingredients: 'Chicken doner, BBQ sauce, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'zurna-tavuk-doner-durum': {
    name: 'Zurna Chicken Doner Wrap',
    description: 'Long zurna chicken doner wrap with special Katik sauce and greens.',
    ingredients: 'Chicken doner, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'katik-mantarli-tavuk-doner-durum': {
    name: 'Katik Mushroom Chicken Doner Wrap',
    description: 'Chicken doner wrap with delicious mushroom sauce and greens.',
    ingredients: 'Chicken doner, mushroom sauce, special Katik sauce, wheat flour lavash (contains gluten), greens, spices.'
  },
  'katik-kasarli-tavuk-doner-durum': {
    name: 'Katik Kashar Chicken Doner Wrap',
    description: 'Chicken doner wrap with melted kashar cheese.',
    ingredients: 'Chicken doner, melted kashar cheese, special Katik sauce, wheat flour lavash (contains gluten).'
  },
  'katik-cheddarli-tavuk-doner-durum': {
    name: 'Katik Cheddar Chicken Doner Wrap',
    description: 'Chicken doner wrap with melted cheddar cheese.',
    ingredients: 'Chicken doner, melted cheddar cheese, special Katik sauce, wheat flour lavash (contains gluten).'
  },
  'katik-tavuk-doner-durum': {
    name: 'Katik Chicken Doner Wrap',
    description: 'Standard chicken doner wrap with special Katik sauce.',
    ingredients: 'Chicken doner, special Katik sauce, wheat flour lavash (contains gluten).'
  },
  'ekmek-arasi-et-doner': {
    name: 'Beef Doner Sandwich',
    description: 'Traditional beef doner served inside freshly baked bread.',
    ingredients: 'Beef doner, sandwich bread (contains gluten), onion, parsley, special spices.'
  },
  'zurna-katik-et-doner-durum': {
    name: 'Zurna Beef Doner Wrap',
    description: 'Long zurna beef doner wrap with special Katik sauce.',
    ingredients: 'Beef doner, special Katik sauce, wheat flour lavash (contains gluten).'
  },
  'katik-et-doner-durum': {
    name: 'Katik Beef Doner Wrap',
    description: 'Beef doner wrap with special Katik sauce and spices.',
    ingredients: 'Beef doner, special Katik sauce, wheat flour lavash (contains gluten).'
  },
  'veggie-durum': {
    name: 'Veggie Wrap',
    description: 'A special vegetarian wrap with grilled mushrooms, kashar cheese, and seasonal vegetables.',
    ingredients: 'Grilled mushrooms, kashar cheese, seasonal vegetables, wheat flour lavash (contains gluten).'
  },
  'kutu-icecekler': {
    name: 'Canned Soft Drinks',
    description: 'Coca-Cola, Fanta, Sprite, Cappy or Ice Tea.',
    ingredients: 'Carbonated water, sugar/sweeteners, acidity regulators, natural flavorings.'
  },
  'ayran': {
    name: 'Ayran',
    description: 'Sutas Ayran (yogurt drink) - 300 ml.',
    ingredients: 'Yogurt, water, salt.'
  },
  'soda': {
    name: 'Mineral Water',
    description: 'Carbonated natural mineral water.',
    ingredients: 'Natural mineral water.'
  },
  'su': {
    name: 'Water',
    description: 'Drinking Water.',
    ingredients: 'Pure water.'
  }
};

const i18nData = {
  tr: {
    rez_info_note: "Rezervasyonunuz restorana iletilecektir.<br>Onay için sizi arayabiliriz.",
    alert_title_notification: "Bildirim",
    confirm_title_sure: "Emin misiniz?",
    admin_btn_yes: "Evet",
    admin_lbl_edit_product: "Ürün Düzenle",
    call: "Ara",
    hero_title_1: "Emek, Lezzet, Kalite.",
    hero_subtitle_1: "Özel Katık Soslu Tantuni ve Dönerler",
    hero_title_2: "Doyasıya Lezzet",
    hero_subtitle_2: "Geleneksel lezzetler modern sunumla buluşuyor",
    hero_title_3: "Safranbolu'da Tek",
    hero_subtitle_3: "En taze malzemeler, enfes baharatlar",
    info_delivery_title: "Hızlı Teslimat",
    info_delivery_desc: "Safranbolu Geneline",
    info_hot_title: "Taze & Sıcak",
    info_hot_desc: "Anında Servis",
    info_rez_title: "Kolay Rezervasyon",
    info_rez_desc: "Masa Ayırtın",
    menu_heading: "Menümüz",
    menu_subheading: "Seçkin lezzetlerimizi inceleyin",
    all_products: "Tüm Ürünler",
    no_products: "Kategoride ürün bulunmamaktadır.",
    about_heading: "Hakkımızda",
    about_subheading: "Eşsiz Lezzet Yolculuğu",
    about_text_1: "Dayı Katık Tantuni & Döner olarak, Safranbolu'da en kaliteli malzemelerle hazırladığımız nefis dürüm ve döner çeşitlerimizle hizmetinizdeyiz. Misafirlerimize her zaman taze, sıcak ve lezzetli ürünler sunmak bizim önceliğimizdir.",
    about_text_2: "Özel soslarımız ve geleneksel pişirme yöntemlerimizle hazırladığımız tantuni ve dönerlerimizle, lezzet standardımızı her geçen gün daha da yukarı taşıyoruz. Sizleri de bu lezzet şölenine ortak olmaya davet ediyoruz.",
    rez_heading: "Rezervasyon Yapın",
    rez_subheading: "Masanızı önceden ayırtın, sıra beklemeden lezzetin tadını çıkarın.",
    lbl_person: "Kişi Sayısı",
    lbl_date: "Tarih Seçin",
    lbl_time: "Saat Seçin",
    lbl_fullname: "Ad Soyad",
    lbl_phone: "Telefon Numarası",
    lbl_note: "Not (Alerji, çocuk sandalyesi vb.)",
    btn_book: "Rezervasyon Yap",
    contact_heading: "İletişim Bilgileri",
    contact_address_lbl: "Adresimiz",
    contact_address_val: "Emek Mah. 75. Yıl Cad. Safranbolu / Karabük",
    contact_phone_lbl: "Telefon",
    contact_hours_lbl: "Çalışma Saatleri",
    contact_hours_val: "Hafta İçi & Hafta Sonu: 11:00 - 22:00",
    footer_text: "© 2025 Dayı Katık Tantuni & Döner · Safranbolu",
    select_day: "Gün",
    select_month: "Ay",
    select_year: "Yıl",
    select_hour: "Seçin",
    nutrition_facts: "Besin Değerleri",
    allergen_info: "Alerjen Bilgisi",
    ingredients: "İçindekiler",
    energy: "Enerji (kcal)",
    fat: "Yağ (g)",
    saturated_fat: "- Doymuş Yağ (g)",
    carbs: "Karbonhidrat (g)",
    sugars: "- Şekerler (g)",
    fiber: "Lif (g)",
    protein: "Protein",
    salt: "Tuz (g)",
    macro_dist: "Makro Dağılımı",
    allergen_warn_title: "Alerjen Uyarısı",
    no_allergens: "Herhangi bir alerjen madde tespit edilmemiştir.",
    cross_contamination_warn: "Alerjen bilgilerimiz çapraz bulaşma riski içerebilir.",
    no_additives: "Katkı maddesi içermez",
    cooked_weight_info: "Ürün gramajları pişmiş halde hesaplanmıştır.",
    vat_included: "Fiyatlarımıza KDV dahildir.",
    rights_reserved: "Fiyat ve içerik değişiklik hakkı saklıdır.",
    tagline: "Lezzet bizim işimiz!",
    detail_btn: "Detay",
    ph_name: "Adınızı ve soyadınızı girin...",
    ph_phone: "05xx xxx xx xx",
    ph_note: "Varsa özel isteklerinizi yazın...",
    form_product_name_placeholder_tr: "Örn: Zurna Tavuk",
    form_product_name_placeholder_en: "Örn: Zurna Chicken",
    form_category_name_example: "Örn: Tatlılar",
    form_category_slug_example: "Örn: tatlilar",
    ph_gram: "Gram...",
    ph_price: "Örn: 180",
    ph_energy: "Örn: 650",
    brand_name: "Dayı Katık",
    rez_success: "Rezervasyonunuz başarıyla alındı! Teşekkür ederiz.",
    rez_error: "Bağlantı hatası. Lütfen telefonla arayın: 0370 712 4747",
    admin_login: "Yönetici Girişi",
    admin_pwd_lbl: "Şifre",
    admin_btn_login: "Giriş Yap",
    order_online: "Online sipariş",
    admin_btn_cancel: "Vazgeç",
    bottom_nav_book: "Rezerve",
    bottom_nav_menu: "Menü",
    bottom_nav_order: "Sipariş",
    bottom_nav_call: "Ara",
    bottom_nav_contact: "İletişim",
    sec_tag_contact: "Bize Ulaşın",
    btn_open_maps: "Google Maps'te Aç",
    order_getir: "Getir'den Sipariş Ver",
    order_phone: "Telefonla Sipariş",
    monday: "Pazartesi",
    tuesday: "Salı",
    wednesday: "Çarşamba",
    thursday: "Perşembe",
    friday: "Cuma",
    saturday: "Cumartesi",
    sunday: "Pazar",
    btn_see_menu: "Menüyü Gör",
    ok: "Tamam",
    hero_title_main: "Gerçek<br><em>Lezzet</em><br>Her Lokmada",
    hero_sub_main: "Tantuni, döner ve dürümde Safranbolu'nun en sevilen adresi.",
    hero_badge_text: "Safranbolu'nun Gözdesi",
    all_categories: "Tüm Kategoriler",
    ph_admin_pwd: "Şifrenizi girin...",
    ph_admin_search: "Ürünlerde ara...",
    admin_panel_title: "Yönetim Paneli",
    admin_tab_prod: "Ürün Yönetimi",
    admin_tab_rez: "Rezervasyonlar",
    admin_add_product: "Yeni Ürün Ekle",
    admin_category_not_found: "Aradığınız kategoriyi bulamadınız mı?",
    admin_add_category_btn: "Yeni Kategori Ekle",
    admin_lbl_category_name: "Kategori Adı",
    ph_category_name_example: "Örn: Tatlılar",
    admin_lbl_category_slug: "Kategori Kodu (Küçük harf, ingilizce karakter)",
    ph_category_slug_example: "Örn: tatlilar",
    admin_lbl_category_icon: "SVG İkon Kodu (Boş bırakılırsa varsayılan ikon atanır)",
    admin_lbl_prod_name_tr: "Ürün Adı (Türkçe)",
    admin_lbl_prod_name_en: "Ürün Adı (İngilizce - English)",
    admin_lbl_prod_price: "Fiyat (TL)",
    admin_lbl_select_category: "Kategori Seçin",
    admin_lbl_prod_image: "Görsel URL veya Dosya Yükle",
    ph_prod_image: "Fotoğraf linki veya dosya...",
    admin_btn_select_file: "Dosya Seç",
    admin_lbl_prod_desc_tr: "Açıklama (Türkçe)",
    ph_prod_desc_tr: "Ürün açıklaması...",
    admin_lbl_prod_desc_en: "Açıklama (İngilizce - English)",
    ph_prod_desc_en: "Product description...",
    admin_lbl_nutrition_section: "Besin Değerleri & Makrolar",
    admin_lbl_portion_tr: "Porsiyon Ölçüsü (Türkçe)",
    ph_portion_tr: "Örn: 1 Porsiyon - 350 g",
    admin_lbl_portion_en: "Porsiyon Ölçüsü (İngilizce - English)",
    ph_portion_en: "Örn: 1 Portion - 350 g",
    admin_lbl_other_info: "Diğer Bilgiler",
    admin_lbl_ingredients_tr: "İçindekiler (Türkçe)",
    ph_ingredients_tr: "Tavuk eti, lavaş, sos, marul...",
    admin_lbl_ingredients_en: "İçindekiler (İngilizce - English)",
    ph_ingredients_en: "Chicken meat, wrap, sauce, lettuce...",
    admin_lbl_no_additives_checkbox: "Katkı Maddesi İçermez işareti gösterilsin",
    admin_lbl_allergens: "Alerjenler (Seçmek için üzerlerine tıklayın)",
    admin_btn_save: "Save",
    alg_sut: "Süt / Laktoz",
    alg_yumurta: "Yumurta",
    alg_gluten: "Gluten",
    alg_hardal: "Hardal",
    alg_kereviz: "Kereviz",
    alg_soya: "Soya",
    alg_susam: "Susam"
  },
  en: {
    rez_info_note: "Your reservation will be forwarded to the restaurant.<br>We may call you for confirmation.",
    alert_title_notification: "Notification",
    confirm_title_sure: "Are you sure?",
    admin_btn_yes: "Yes",
    admin_lbl_edit_product: "Edit Product",
    call: "Call",
    hero_title_1: "Labor, Taste, Quality.",
    hero_subtitle_1: "Special Katik Sauced Tantuni and Doners",
    hero_title_2: "Delicious Feast",
    hero_subtitle_2: "Traditional tastes meet modern presentation",
    hero_title_3: "Unique in Safranbolu",
    hero_subtitle_3: "The freshest ingredients, delicious spices",
    info_delivery_title: "Fast Delivery",
    info_delivery_desc: "Across Safranbolu",
    info_hot_title: "Fresh & Hot",
    info_hot_desc: "Instant Service",
    info_rez_title: "Easy Reservation",
    info_rez_desc: "Book a Table",
    menu_heading: "Our Menu",
    menu_subheading: "Browse our select delicacies",
    all_products: "All Products",
    no_products: "No products found in this category.",
    about_heading: "About Us",
    about_subheading: "A Unique Taste Journey",
    about_text_1: "As Dayi Katik Tantuni & Doner, we are at your service in Safranbolu with our delicious wrap and doner varieties prepared with the highest quality ingredients. Serving fresh, hot, and tasty products to our guests is always our priority.",
    about_text_2: "With our tantuni and doners prepared with our special sauces and traditional cooking methods, we raise our taste standards day by day. We invite you to share this feast of taste.",
    rez_heading: "Book a Table",
    rez_subheading: "Book your table in advance, enjoy the taste without waiting in line.",
    lbl_person: "Number of Guests",
    lbl_date: "Select Date",
    lbl_time: "Select Time",
    lbl_fullname: "Full Name",
    lbl_phone: "Phone Number",
    lbl_note: "Note (Allergies, high chair, etc.)",
    btn_book: "Book Table",
    contact_heading: "Contact Information",
    contact_address_lbl: "Address",
    contact_address_val: "Emek Mah. 75. Yil Cad. Safranbolu / Karabuk",
    contact_phone_lbl: "Phone",
    contact_hours_lbl: "Opening Hours",
    contact_hours_val: "Weekdays & Weekends: 11:00 - 22:00",
    footer_text: "© 2025 Dayi Katik Tantuni & Doner · Safranbolu",
    select_day: "Day",
    select_month: "Month",
    select_year: "Year",
    select_hour: "Select",
    nutrition_facts: "Nutrition Facts",
    allergen_info: "Allergen Info",
    ingredients: "Ingredients",
    energy: "Energy (kcal)",
    fat: "Fat (g)",
    saturated_fat: "- Saturated Fat (g)",
    carbs: "Carbohydrates (g)",
    sugars: "- Sugars (g)",
    fiber: "Fiber (g)",
    protein: "Protein",
    salt: "Salt (g)",
    macro_dist: "Macro Distribution",
    allergen_warn_title: "Allergen Warning",
    no_allergens: "No allergens detected.",
    cross_contamination_warn: "Our allergen information may contain risk of cross-contamination.",
    no_additives: "No additives",
    cooked_weight_info: "Product weights are calculated after cooking.",
    vat_included: "Prices include VAT.",
    rights_reserved: "We reserve the right to change prices and content.",
    tagline: "Taste is our business!",
    detail_btn: "Detail",
    ph_name: "Enter your full name...",
    ph_phone: "05xx xxx xx xx",
    ph_note: "Write special requests if any...",
    form_product_name_placeholder_tr: "e.g., Zurna Chicken (Turkish)",
    form_product_name_placeholder_en: "e.g., Zurna Chicken (English)",
    form_category_name_example: "e.g., Desserts",
    form_category_slug_example: "e.g., desserts",
    ph_gram: "Grams...",
    ph_price: "e.g., 180",
    ph_energy: "e.g., 650",
    brand_name: "Dayi Katik",
    rez_success: "Your reservation has been received successfully! Thank you.",
    rez_error: "Connection error. Please call: 0370 712 4747",
    admin_login: "Admin Login",
    admin_pwd_lbl: "Password",
    admin_btn_login: "Login",
    order_online: "Online order",
    admin_btn_cancel: "Cancel",
    bottom_nav_book: "Book",
    bottom_nav_menu: "Menu",
    bottom_nav_order: "Order",
    bottom_nav_call: "Call",
    bottom_nav_contact: "Contact",
    sec_tag_contact: "Contact Us",
    btn_open_maps: "Open in Google Maps",
    order_getir: "Order from Getir",
    order_phone: "Order by Phone",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    btn_see_menu: "See Menu",
    ok: "OK",
    hero_title_main: "Real<br><em>Taste</em><br>In Every Bite",
    hero_sub_main: "Safranbolu's favorite address for tantuni, doner, and wraps.",
    hero_badge_text: "Safranbolu's Favorite",
    all_categories: "All Categories",
    ph_admin_pwd: "Enter password...",
    ph_admin_search: "Search products...",
    admin_panel_title: "Admin Panel",
    admin_tab_prod: "Product Management",
    admin_tab_rez: "Reservations",
    admin_add_product: "Add New Product",
    admin_category_not_found: "Can't find the category you're looking for?",
    admin_add_category_btn: "Add New Category",
    admin_lbl_category_name: "Category Name",
    ph_category_name_example: "e.g., Desserts",
    admin_lbl_category_slug: "Category Code (Lowercase, English characters)",
    ph_category_slug_example: "e.g., desserts",
    admin_lbl_category_icon: "SVG Icon Code (Left blank, default icon is assigned)",
    admin_lbl_prod_name_tr: "Product Name (Turkish)",
    admin_lbl_prod_name_en: "Product Name (English)",
    admin_lbl_prod_price: "Price (TL)",
    admin_lbl_select_category: "Select Category",
    admin_lbl_prod_image: "Image URL or Upload File",
    ph_prod_image: "Image link or file...",
    admin_btn_select_file: "Select File",
    admin_lbl_prod_desc_tr: "Description (Turkish)",
    ph_prod_desc_tr: "Product description...",
    admin_lbl_prod_desc_en: "Description (English)",
    ph_prod_desc_en: "Product description...",
    admin_lbl_nutrition_section: "Nutrition Facts & Macros",
    admin_lbl_portion_tr: "Serving Size (Turkish)",
    ph_portion_tr: "e.g., 1 Serving - 350 g",
    admin_lbl_portion_en: "Serving Size (English)",
    ph_portion_en: "e.g., 1 Portion - 350 g",
    admin_lbl_other_info: "Other Info",
    admin_lbl_ingredients_tr: "Ingredients (Turkish)",
    ph_ingredients_tr: "Chicken meat, wrap, sauce, lettuce...",
    admin_lbl_ingredients_en: "Ingredients (English)",
    ph_ingredients_en: "Chicken meat, wrap, sauce, lettuce...",
    admin_lbl_no_additives_checkbox: "Show 'No Additives' label",
    admin_lbl_allergens: "Allergens (Click to select)",
    admin_btn_save: "Save",
    alg_sut: "Milk / Lactose",
    alg_yumurta: "Egg",
    alg_gluten: "Gluten",
    alg_hardal: "Mustard",
    alg_kereviz: "Celery",
    alg_soya: "Soy",
    alg_susam: "Sesame"
  }
};

module.exports = {
  defaultCategoriesMap,
  defaultItemTranslations,
  i18nData
};
